
CREATE OR REPLACE TASK HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_VEHICLE_TELEMETRY
    WAREHOUSE = COMPUTE_WH
    -- AFTER HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_REFRESH_RENTALS
    -- SCHEDULE = '60 MINUTE'
  SCHEDULE = 'USING CRON 0 7 * * * Asia/Jakarta'
AS
CALL HACKATHON_SNOWFLAKE.TRANSPORTATION.SP_VEHICLE_TELEMETRY(DATE(CONVERT_TIMEZONE('Asia/Jakarta', CURRENT_TIMESTAMP())));

-----------

CREATE OR REPLACE TASK HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_RENTALS
    WAREHOUSE = COMPUTE_WH
    -- AFTER HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_REFRESH_MAINTENANCES
  SCHEDULE = 'USING CRON 15 7 * * * Asia/Jakarta'
AS
CALL HACKATHON_SNOWFLAKE.TRANSPORTATION.SP_RENTALS(DATE(CONVERT_TIMEZONE('Asia/Jakarta', CURRENT_TIMESTAMP())));

-----------

CREATE OR REPLACE TASK HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_CUSTOMERS
    WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 7 * * 1 Asia/Jakarta'
AS
CALL HACKATHON_SNOWFLAKE.TRANSPORTATION.SP_CUSTOMERS();

-----------

CREATE OR REPLACE TASK HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_PARENTS_CARS_MAINTENANCE
    WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 7 * * 1 Asia/Jakarta'
AS
SELECT 1;

CREATE OR REPLACE TASK HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_CARS
    WAREHOUSE = COMPUTE_WH
    AFTER HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_PARENTS_CARS_MAINTENANCE
  -- SCHEDULE = 'USING CRON 0 7 1 * * Asia/Jakarta'
AS
CALL HACKATHON_SNOWFLAKE.TRANSPORTATION.SP_CARS();


CREATE OR REPLACE TASK HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_MAINTENANCES
    WAREHOUSE = COMPUTE_WH
  -- SCHEDULE = 'USING CRON 0 7 1 * * Asia/Jakarta'
  AFTER HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_PARENTS_CARS_MAINTENANCE
AS
CALL HACKATHON_SNOWFLAKE.TRANSPORTATION.SP_MAINTENANCES();


CREATE OR REPLACE TASK HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_MAINTENANCES_INFO
    WAREHOUSE = COMPUTE_WH
    AFTER HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_CARS,
        HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_MAINTENANCES
  -- SCHEDULE = 'USING CRON 0 7 1 * * Asia/Jakarta'
AS
CALL HACKATHON_SNOWFLAKE.TRANSPORTATION.SP_MAINTENANCES_INFO();



-- SHOW TASKS 
-- DROP TASK HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_REFRESH_VEHICLE_TELEMETRY
-- ALTER TASK TASK_MAINTENANCES_INFO RESUME;
-- ALTER TASK TASK_REFRESH_VEHICLE_TELEMETRY SUSPEND;
-- EXECUTE TASK HACKATHON_SNOWFLAKE.TRANSPORTATION.TASK_VEHICLE_TELEMETRY;

-- # __________ minute (0-59)
-- # | ________ hour (0-23)
-- # | | ______ day of month (1-31, or L)
-- # | | | ____ month (1-12, JAN-DEC)
-- # | | | | __ day of week (0-6, SUN-SAT, or L)
-- # | | | | |
-- # | | | | |
--   * * * * *
  
